INCLUDE Variables.ink
INCLUDE Vale.ink
INCLUDE Horace.ink
INCLUDE Foxes.ink
INCLUDE Klay.ink
INCLUDE Davey.ink
INCLUDE Intro.ink
INCLUDE ClayPieceGet.ink
INCLUDE ClayPieceGet2.ink
INCLUDE ClayPieceGet3.ink
INCLUDE ClayPieceGet4.ink
INCLUDE ClayPieceGet5.ink