// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2025 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.3.62f2";
    extern const char* const UnityVersionDigits = "2022.3.62";
    extern const char* const UnityVersionSuffix = "f2";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 62;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.3.62f2_7670c08855a9";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.3.62f2_7670c08855a9";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.3.62f2 (7670c08855a9)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 7762112;

    extern const UInt64 UnityVersionDate = 1758882447;
    extern const char* const UnityVersionBranch = "2022.3/respin/2022.3.62f2-4af31df585-v2";
    extern const char* const UnityVersionDisplay = "2022.3.62f2";
    extern const char* const UnityVersionDisplay_Verbose = "2022.3.62f2.git.7762112";
    extern const char* const UnityVersionRevision = "7670c08855a9";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.3.62f2 (7670c08855a9)";
    extern const wchar_t* const L_UnityVersion = L"2022.3.62f2";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2025 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 62
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.3.62f2_7670c08855a9"
    #define UNITY_VERSION_PARENS_HASH "2022.3.62f2 (7670c08855a9)"
    #define UNITY_VERSION_BLD 7762112
    #define UNITY_VERSION_WIN "2022.3.62.7762112"

#endif // !RC_INVOKED
