===Klay===

Oh...uh...hi!
Down here...!
Sorry...I'm a bit...
...small.
At least nowadays I am.
I hope you don't hurt your neck looking down at me for so long.
You might as well spare yourself the pain and head out now.

*Wait! Who are you?
-> Branch5_1_1
*I have strong neck muscles, don't worry about it.
-> Branch5_1_9
*Your eagerness for me to leave makes it less fun to actually do it.
-> Branch5_1_13

= Branch5_1_1
Me?
Oh...uh...
I'm Klay...!
...
That's me...so...
You're...staying...um...
Ah! You're a human!
You must want a sculpture!

*A sculpture? What for?
-> Branch5_1_2
*Yeah! That's exactly what I wanted!
-> Branch5_1_5
*Not really.
-> Branch5_1_7

= Branch5_1_9
Oh...uh...
...really?
Uh...I guess you can talk to me if you want...
I probably won't be too fun though...
I'm afraid those days are behind me.
You should've come a little sooner hahaha...
Back when I used to be bigger...
I mean I can try...you're welcome to stick around! I'm just saying...

*You used to be bigger...?
-> Branch5_1_10
*Did you just suddenly become not fun or something?
-> Branch5_1_11
*Yeah...you are kinda boring...
-> Branch5_1_12

= Branch5_1_13
Oh...sorry...
Or...? Not sorry...?
I don't know anymore...
Trust me, I used to be a lot more fun than this.
At least the humans thought so.
They were just like you, you know.
Only chatting with me when they want something.
I mean...not that I won't...give you...something?
What did you want exactly?

*Oh, I was just saying hi.
-> Branch5_1_14
*You used to talk with other humans?
-> Branch5_1_15
*To mess with you for the most part.
-> Branch5_1_16

= Branch5_1_2
Your machine...!
All of the humans used to want sculptures and stuff like that from me.
Then they'd put it into their machine and it would make more...!
More art! Without me...
...
But...! It would eventually run out!
You know...it would spit out the same stuff and they didn't like that...
So they'd come back to me for more...!
I would use myself to make stuff for them, pictures, sculptures...
It got harder to come up with ideas when I started to get smaller...
But I kept going and then eventually when I got too small they just...
...left.
Maybe they had enough ideas.
I know I don't anymore...
I used to be so...
...creative!
I guess nobody needs that anymore, huh?
-> Branch5_1_2_2

= Branch5_1_2_2
*That's not true.
-> Branch5_1_3
*Maybe we can put you back together somehow.
-> Branch5_1_6
*Probably.
-> Branch5_1_8

= Branch5_1_5
Okay...!
Uh...one second...!
...
...
...
Sorry...it's coming...
...
...
...
Darn...!
I'm sorry...
There's just not enough of me...
And when there's not enough of me...I don't have any ideas.
I used to be able to come up with art like that!
But after the humans kept stuffing parts of me into their machine...
...there wasn't enough left of me to keep creating.
I was all of their ideas...the food for their machine to make more copies of me...
...but I'm just useless now...
-> Branch5_1_2_2

= Branch5_1_7
Oh...
I thought that's what you humans liked.
You know...for your machine...?
To make more art...?
Well...I guess I wouldn't be that helpful now anyways.
Even if you did want a sculpture, I don't think there's enough of me to make one...
I'm too small and too small means not enough of me and no ideas.
Luckily you don't want that though...
Oh! But you don't have to go though!
I can do other things...!
Like...uh...
Darn...!
I can't even come up with anything else...!
I guess the only good thing about me was my art...
Now that I don't even have that anymore you probably think I'm just...
...lame.
Don't worry...I agree with you.
I'm useless.
-> Branch5_1_2_2

= Branch5_1_10
Yeah...!
I know I'm just a blob of clay now, but I used to be taller that you...!
Back when I had ideas!
Then that machine came along...
They thought they could make more of me.
That if they put enough of me in, they'd come up with something...
...great!
They just made me smaller though...
And smaller me means less ideas for them so i guess they kinda screwed that up a lot...
And me too I guess...
I've tried to lighten this place up before...like restore it and all...
I wanted a new purpose.
But there's not enough of me to go around anymore.
I couldn't even figure out where to start let alone come up with a way to redecorate...
I miss when I used to be able to do that...
Maybe if I hadn't taken this job...
I wouldn't be so useless now...
-> Branch5_1_2_2

= Branch5_1_11
No...
It was...slow...
I would come up with an idea...
Make a sculpture out of it...out of me...
Then the humans would take it.
They'd put it in their machine and it would make copies...
Or at least smush around the pieces of me and call it something new...
Things become less fun when you see that...
A machine that's...somehow better than you even though it couldn't exist without you...
And then the smaller you get, the harder it gets, but the humans keep wanting more...
It made their machine better...they would say.
I...wished they'd say that I was as good as it was some days...
So my fun didn't suddenly go away...
I don't even think my fun went away...
Just my creativity...
That's what brought the fun.
And now I'm useless.
-> Branch5_1_2_2

= Branch5_1_12
...
Thanks...?
Trust me...
I wish I wasn't so boring.
I used to be the most creative one here.
People would praise me for it all day long...!
Until they got their machine...
Then it was the most creative...
I'm not usually competitive, but...
They would just take my sculptures and give it to the machine...
It would just give them a smudged version of what I'd already made.
I could tell because there was a piece of me in every picture and sculpture I gave them.
It's how I got so small...
So if you think I'm boring, I know I am...
All of my passion left me with every chunk of myself they put into their machine.
Now I'm nothing.
Useless...
-> Branch5_1_2_2

= Branch5_1_14
Oh...um...hi...?
...
You really are like them, huh...?
You know, I haven't seen a human around since their machine was still on.
Are you here to turn it back on or something...?
No...then why would you be talking with me?
I gave them the pictures and pieces of myself that actually made it run.
Sure, you could turn it back on, but without me you won't get anything out of it.
Unless...you just stuff the rest of me in there...
...
Please don't do that...
You know, I used to be taller, more creative...
Before the machine I mean...
Even if you wanted to shove me into that machine...
I don't have any creative juices flowing in me anymore.
I'm useless.
-> Branch5_1_2_2

= Branch5_1_15
Yeah...
Can't say I'm too big of a fan...no offense...
The ones that worked here at least are the reason I'm like this...
Small...no more ideas...an uncreative blob...
All because of that machine.
They would tell me it was the future and that they wouldn't need people like me when it was done...
That I wouldn't need to make art...
But that always confused me...
I always liked making my art...
And the machine could only spit out art itself after they put a little chunk of me into it.
I could tell because I could see my purple clay in everything it made.
It just smudged it in enough that nobody cared. They thought it was amazing...
...
I don't understand humans...
They took from me just to make what I would've anyways...
And now I'm useless.
-> Branch5_1_2_2

= Branch5_1_16
Oh...
Again...I may not really be that fun...
I used to be able to act, you know.
I could've at least acted believably if you wanted to prank me...
I could've a long time ago I mean.
I'm sure if you find that machine that the humans made though...
...there may still be recordings of me acting and art and music.
I used to make tons of art for them.
I would give them the chunk of myself that the idea came from and they'd give it to their machine.
And it would make more...!
Without me...
I...don't have any more chunks to give away is what I'm saying...
I'm not as big as I used to be...
So if you want to mess with someone...
Maybe you'd have better luck with someone less...
...useless.
-> Branch5_1_2_2

= Branch5_1_3
I mean...it is though...
But...I guess there may be a way to fix it...
A way to make me bigger and get some ideas for my art again...!
There are probably chunks of me laying around here...
If you find any...bring them back to me...
And I can see if it'll get me back to my old self!
I'll even make you something...!
That is...if you can find 9 pieces of me laying around...
Ah...! You don't need too though...!
I mean...it would help...but I won't be mad if...
Um...it would just be nice to be myself again...!
So if you do find any clay around here...I'll gladly take it back...
Or don't...! I don't want to be a bother!
Anyways...!
-> Branch5_1_4

= Branch5_1_4
I'll...see you around...!
->END

= Branch5_1_6
Put me back together...?
You really want to do that...?
I wouldn't want to be a bother...
But if you're offering...
There should be pieces of me laying around here...
9 exactly...
If you could find them, then maybe I could put myself back together again...
And I could make art again...!
I could even make you something!
Only...if you want to do that...
I'd be...very thankful if you did...
Either way though...thanks for stopping by...
It's been a while since someone actually talked with me.
-> Branch5_1_4

= Branch5_1_8
Oh...uh...thanks...
Hey...
...if you want to be around someone more fun to talk to...
...you could always help me find some pieces of myself.
They're...always too high up for me...
But there's 9 pieces...
If you find them I'll be bigger again...!
And less useless...!
If you want me to be less useless that is...
You don't have to do anything I guess...
Maybe I'll make you some art for your trouble.
Until then though, I'll just be hanging around here.
It's not like I can get any smaller...!
-> Branch5_1_4


















